{% set name = "grapheme" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grapheme-{{ version }}.tar.gz
  sha256: 44c2b9f21bbe77cfb05835fec230bd435954275267fea1858013b102f8603cca

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  skip: True # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - grapheme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alvinlindstam/grapheme
  summary: A python package for grapheme aware string handling
  description: |
    A Python package for working with user perceived characters. More specifically, 
    string manipulation and calculation functions for working with grapheme 
    cluster groups (graphemes) as defined by the Unicode Standard Annex #29.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://grapheme.readthedocs.io/
  dev_url: https://github.com/alvinlindstam/grapheme

extra:
  recipe-maintainers:
    - Brainor
